<h1>Receive your file</h1>
<?php
include(dirname(__FILE__) . '/edit-wizard.phtml');
?>
<div class="center">
    <div class="col-lg-3"><a href="/edit/upload/?key=<?php echo $newKey;?>" class="btn btn-lg btn-primary">Upload file</a></div>
    <div class="col-lg-4"><a href="/edit/send-email/" class="btn btn-lg btn-primary">Send to email</a></div>
    <div class="col-lg-3"><a href="/waveform/?key=<?php echo $newKey;?>" class="btn btn-lg btn-primary">Waveform</a></div>
</div>