<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">

    <title>UAWC final stage</title>

    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/styles.css" rel="stylesheet">
    <link href="/css/edit-wizard.css" rel="stylesheet">
</head>

<body>

<script src="/js/jquery-2.1.3.min.js"></script>
<?php
if (isset($template)) {
    include(__DIR__ . "/{$template}.phtml");
} elseif (isset($content)) {
    echo $content;
}
?>


<script src="/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>
