<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">

    <title>UAWC final stage</title>

    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/styles.css" rel="stylesheet">
    <link href="/css/edit-wizard.css" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">UWC VII</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
<!--            <ul class="nav navbar-nav">-->
<!--                <li data-section=""><a href="/">Home</a></li>-->
<!--            </ul>-->
            <ul class="nav navbar-nav navbar-right">
                <li data-section="about"><a href="/about/">About</a></li>
            </ul>
        </div>
    </div>
</nav>

<script src="/js/jquery-2.1.3.min.js"></script>
<div class="container">
    <div class="starter-template">
        <?php
        if (isset($template)) {
            include(__DIR__ . "/{$template}.phtml");
        } elseif (isset($content)) {
            echo $content;
        }
        ?>
    </div>
</div>


<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/js/navigation.js"></script>
</body>
</html>
